version: "3.8"

services:
  fronted:
    build:
      context: ../front
      dockerfile: ../dev-config/Dockerfile.front
    ports:
      - "3000:3000"
    volumes:
      - ../front:/usr/app
    networks:
      - strapi
  cms:
    build: 
      context: ../cms
      dockerfile: ../dev-config/Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ../cms:/usr/app
    networks:
      - strapi
  db: 
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
networks:
  strapi:
volumes:
  db: